# CONSTRAINTS
# [A] DOMAIN CONSTRAINTS
#           Not Null, Default, Check, Enum
# [B] KEY CONSTRAINTS
#           Primary Key, Foreign Key, Unique Key

# [A] DOMAIN CONSTRAINTS-
CREATE TABLE students(
Roll_no INT NOT NULL,
Name VARCHAR (100) DEFAULT"-",
Age INT CHECK(Age>=18),
Gender ENUM('M','F')
);

INSERT INTO students VALUES(1,'A',21,'F');
INSERT INTO students VALUES(2,'B',22,'M');
INSERT INTO students VALUES(3,'C',33,'M');
INSERT INTO students VALUES (4,'D',28,'F');

SELECT * FROM STUDENTS;

# [B] KEY CONSTRAINTS-
# PRIMARY KEY AND FOREIGN KEY
CREATE TABLE Emp(
Emp_ID INT PRIMARY KEY,
Name VARCHAR(100),
Age INT);

INSERT INTO Emp Values (1,"A",25);
INSERT INTO Emp Values (2,"B",30);
INSERT INTO Emp Values (3,"C",34);
INSERT INTO Emp Values (4,"D",26);
INSERT INTO Emp Values (5,"E",29);

SELECT * FROM Emp;

CREATE TABLE Dept(
Dept_ID INT PRIMARY KEY,
Dept_Name VARCHAR (100),
EID INT,
FOREIGN KEY (EID) REFERENCES Emp(Emp_ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);

INSERT INTO Dept VALUES (101,"HR",4);
INSERT INTO Dept VALUES (102,"Mktg",1);
INSERT INTO Dept VALUES (103,"Finance",3);

UPDATE Emp SET Emp_ID = 3000 WHERE Emp_ID = 3;
DELETE FROM Emp WHERE Emp_ID = 3000;

SELECT * FROM Dept;

# UNIQUE KEY
CREATE TABLE Emp1(
Emp_ID INT UNIQUE,
Name VARCHAR(100),
Age INT
);

INSERT INTO Emp1 VALUES(1,"A",20);
INSERT INTO Emp1 VALUES(2,"B",32);
INSERT INTO Emp1 VALUES(3,"C",23);
INSERT INTO Emp1 VALUES(4,"D",31);
INSERT INTO Emp1 VALUES(null,"E",35);

SELECT * FROM EMP1;
